clean: true
sdk: iphonesimulator
xcodebuild_arguments:
 - -workspace
 - VerIDUI.xcworkspace
 - -scheme
 - VerIDUI
 - -sdk
 - iphonesimulator
author: Applied Recognition, Inc.
module: VerIDUI
min_acl: public
exclude: ZIPFoundation/*
skip_undocumented: true
hide_documentation_coverage: true
custom_categories:
 - name: Session
   children:
   - VerIDSession
   - VerIDSessionDelegate
   - VerIDSessionViewDelegate
   - TranslatedStrings
 - name: View Controllers
   children:
   - SessionViewControllersFactory
   - VerIDViewControllerProtocol
   - VerIDViewControllerDelegate
   - VerIDViewController
   - ResultViewControllerProtocol
   - ResultViewControllerDelegate
   - TipsViewControllerProtocol
   - TipsViewControllerDelegate
   - FaceDetectionAlertControllerProtocol
   - FaceDetectionAlertControllerDelegate
   - CameraViewController
