project 'Ver-ID Sample.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Ver-ID Sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Ver-ID Sample

  pod 'Ver-ID-UI'
end
